name: appcenter_crashes
description: Visual Studio App Center (Crashes) plugin for Flutter applications.
version: 0.0.1
author: Aloïs Deniel<alois.deniel@outlook.com>
homepage: https://github.com/aloisdeniel/flutter_plugin_appcenter

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.aloisdeniel.flutter.appcenter_crashes
    pluginClass: AppcenterCrashesPlugin
